# experiment_paths_and_parameters

TwoWeek2023:
  dataPathMain: 2 week old - pairs # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - pairs # path for the CSV with image scale
  imageScaleFilename: ArenaCenters_SocPref_3456.csv
  imageScaleColumn: 4 # column (0-indexed) with image scale
  datasetColumns:  [0] # columns to concatenate to match dataset name 
  # filename of CSV file *in each data folder* with image offset filename
  datasetRemoveStrings: ['results_', 'SocPref_', '_ALL', '_light', '_dark', '_2wpf', '_SocPref'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information 
  arenaCentersPathName: 2 week old - pairs
  arenaCentersFilename: ArenaCenters_SocPref_3456.csv
  arenaCentersColumns: [5,6] # columns (0-indexed) with x,y arena centers

TwoWeekDark2023:
  dataPathMain: 2 week old - pairs in the dark # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - pairs in the dark # path for the CSV with image scale
  imageScaleFilename: ArenaCenters_SocPref_3456.csv
  imageScaleColumn: 4 # column (0-indexed) with image scale
  datasetColumns:  [0] # columns to concatenate to match dataset name 
  # filename of CSV file *in each data folder* with image offset filename
  datasetRemoveStrings: ['results_', 'SocPref_', '_ALL', '_light', '_dark', '_2wpf', '_SocPref'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information 
  arenaCentersPathName: 2 week old - pairs in the dark
  arenaCentersFilename: ArenaCenters_SocPref_3456.csv
  arenaCentersColumns: [5,6] # columns (0-indexed) with x,y arena centers


CA2024:
  dataPathMain: 2 week old - pairs - cholic acid # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - pairs - cholic acid
  imageScaleFilename: ImageScale_SocPrefBA_3b_all.csv
  imageScaleColumn: 4 # column (0-indexed) with image scale
  datasetColumns:  [0] # columns to concatenate to match dataset name 
  datasetRemoveStrings: ['results_'] # strings to remove from filenames and first column of the imageScale CSV to find matches.
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information
  arenaCentersLocation:  # estimate from well offset positions
  arenaCentersColumns: 
  subGroups: ['Condition1', 'Condition2'] # optional, strings of subFolder names of sub-experiments with the same overall parameters
  
Solitary_Cohoused_March2024:
  dataPathMain: TwoWeekOld_Solitary_CoHoused_1_3-2-2024 # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: TwoWeekOld_Solitary_CoHoused_1_3-2-2024
  imageScaleFilename: SocDef_Solitary_AnalysisRaghu.csv
  imageScaleColumn: 4 # column (0-indexed) with image scale
  datasetColumns:  [0] # columns to concatenate to match dataset name 
  datasetRemoveStrings: ['SocDef_', 'results_'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information
  arenaCentersLocation:  # estimate from well offset positions
  arenaCentersColumns: 
  subGroups: ['Condition1', 'Condition2'] # optional, strings of subFolder names of sub-experiments with the same overall parameters
  
Shank3_Feb2024:
  dataPathMain: 2 week old - pairs with shank3 mutations # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - pairs with shank3 mutations
  imageScaleFilename: SocDef_Shank3_AnalysisRaghu.csv
  imageScaleColumn: 4 # column (0-indexed) with image scale
  datasetColumns: [0, 1] #  columns to concatenate to match dataset name 
  datasetRemoveStrings: ['SocDef_', 'results_'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information
  arenaCentersLocation:  # estimate from well offset positions
  arenaCentersColumns: 
  subGroups: ['Genotype 1', 'Genotype 2', 'Genotype 3'] # optional, strings of subFolder names of sub-experiments with the same overall parameters
  
Infected_housing_March2024:
  dataPathMain: 2 week old - infected versus non-infected, solitary versus co-housed pairs # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - infected versus non-infected, solitary versus co-housed pairs
  imageScaleFilename: SocDist_1a_CorrespondingTables.csv
  imageScaleColumn: 1 # column (0-indexed) with image scale
  datasetColumns:  [0, 2]  # columns to concatenate to match dataset name
  datasetRemoveStrings: ['SocDist_', 'SocDef_', 'Solitary_', 'results_'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information
  arenaCentersLocation:  # estimate from well offset positions
  arenaCentersColumns: 
  subGroups: ['C1_G1_nonInfect_coHoused', 'C1_G2_nonInfect_solitary', 'C2_G1_Infected_coHoused', 'C2_G2_Infected_solitary'] # optional, strings of subFolder names of sub-experiments with the same overall parameters
  
XGF_May2024:
  dataPathMain: 2 week old - conventionalized versus ex-germ-free fish # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - conventionalized versus ex-germ-free fish
  imageScaleFilename: SocDef_XGF_AnalysisRaghu_Filtered_mod.csv
  imageScaleColumn: 4 # column (0-indexed) with image scale
  datasetColumns:  [0, 1] # columns to concatenate to match dataset name 
  datasetRemoveStrings: ['SocDist_', 'SocDef_', 'Solitary_', 'results_'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information
  arenaCentersLocation:  # estimate from well offset positions
  arenaCentersColumns: 
  subGroups: ['XGF_filteredCSVs_1', 'XGF_filteredCSVs_2'] # optional, strings of subFolder names of sub-experiments with the same overall parameters
  
Infected_May2024:
  dataPathMain: 2 week old - infected versus non-infected pairs # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - infected versus non-infected pairs
  imageScaleFilename: SocDist_2a_RaghuAnalysis_mod.csv
  imageScaleColumn: 5 # column (0-indexed) with image scale
  datasetColumns:  [0,1] # columns to concatenate to match dataset name 
  datasetRemoveStrings: ['SocDist_', 'results_'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information
  arenaCentersLocation:  # estimate from well offset positions
  arenaCentersColumns: 
  subGroups: ['infected_nonInfected_1', 'infected_nonInfected_2', 'infected_nonInfected_3'] # optional, strings of subFolder names of sub-experiments with the same overall parameters

TwoWeek2023_test:
  dataPathMain: 2 week old - pairs TestSubset # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - pairs TestSubset
  imageScaleFilename: ArenaCenters_SocPref_3456.csv
  imageScaleColumn: 4 # column (0-indexed) with image scale
  datasetColumns:  [0] # columns to concatenate to match dataset name 
  datasetRemoveStrings: ['results_', 'SocPref_', '_ALL', '_light', '_dark', '_2wpf', '_SocPref'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  # Arena center location information
  arenaCentersPathName: 2 week old - pairs TestSubset
  arenaCentersFilename: ArenaCenters_SocPref_3456.csv
  arenaCentersColumns: [5,6] # columns (0-indexed) with x,y arena centers
  # filename of CSV file *in each data folder* with image offset filename
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv

Shank3_Feb2024_testSubset:
  dataPathMain: 2 week old - shank3 mutations TEST subset # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  image scale:   # image scale, um/px, or empty  to load from file
  imageScalePathName: 2 week old - shank3 mutations TEST subset
  imageScaleFilename: SocDef_Shank3_AnalysisRaghu.csv
  imageScaleColumn: 4 # column (0-indexed) with image scale
  datasetColumns: [0,1] # columns to concatenate in the  imageScale CSV to match dataset name .
  datasetRemoveStrings: ['SocDef_', 'results_'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information:
  arenaCentersLocation:  # None; estimate from well offset positions
  arenaCentersColumns: 
  subGroups: ['Genotype 1', 'Genotype 2', 'Genotype 3'] # optional, strings of subFolder names of sub-experiments with the same overall parameters


Gut_Transmission_0b:
  dataPathMain: 2 week old - pairs assayed for gut transmission 0b # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - pairs assayed for gut transmission 0b
  imageScaleFilename: SocBehTransm_0b_Log.csv
  imageScaleColumn: 4 # column (0-indexed) with image scale
  datasetColumns:  [0,1] # columns to concatenate to match dataset name 
  datasetRemoveStrings: ['SocBehTransm_', 'results_'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information
  arenaCentersLocation:  # estimate from well offset positions
  arenaCentersColumns: 
  subGroups: ['Group_1', 'Group_2'] # optional, strings of subFolder names of sub-experiments with the same overall parameters


Gut_Transmission_0c:
  dataPathMain: 2 week old - pairs assayed for gut transmission 0c # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - pairs assayed for gut transmission 0c
  imageScaleFilename: SocBehTransm_0c_Log.csv
  imageScaleColumn: 4 # column (0-indexed) with image scale
  datasetColumns:  [0,1] # columns to concatenate to match dataset name 
  datasetRemoveStrings: ['SocBehTransm_', 'results_'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information
  arenaCentersLocation:  # estimate from well offset positions
  arenaCentersColumns: 
  subGroups: ['Group_1', 'Group_2'] # optional, strings of subFolder names of sub-experiments with the same overall parameters
  
SingleFish_Light_July2024:
  dataPathMain: 2 week old - single fish # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - single fish # path for the CSV with image scale
  imageScaleFilename: SocPref_4a-b_AnalysisRaghu.csv
  imageScaleColumn: 3 # column (0-indexed) with image scale
  datasetColumns:  [0] # columns to concatenate to match dataset name 
  # filename of CSV file *in each data folder* with image offset filename
  datasetRemoveStrings: ['results_', 'SocPref_', '_ALL', '_light', '_dark', '_2wpf', '_SocPref'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information 
  arenaCentersLocation:  # estimate from well offset positions
  arenaCentersColumns: 

SingleFish_Dark_July2024:
  dataPathMain: 2 week old - single fish in the dark # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - single fish in the dark # path for the CSV with image scale
  imageScaleFilename: SocPref_6a-b_AnalysisRaghu.csv
  imageScaleColumn: 3 # column (0-indexed) with image scale
  datasetColumns: [0] # columns to concatenate to match dataset name 
  # filename of CSV file *in each data folder* with image offset filename
  datasetRemoveStrings: ['results_', 'SocPref_', '_ALL', '_light', '_dark', '_2wpf', '_SocPref'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information 
  arenaCentersLocation:  # estimate from well offset positions
  arenaCentersColumns: 


SingleFish_Light_July2024_subset:
  dataPathMain: 2 week old - single fish - subset # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - single fish - subset # path for the CSV with image scale
  imageScaleFilename: SocPref_4a-b_AnalysisRaghu.csv
  imageScaleColumn: 3 # column (0-indexed) with image scale
  datasetColumns:  [0] # columns to concatenate to match dataset name 
  # filename of CSV file *in each data folder* with image offset filename
  datasetRemoveStrings: ['results_', 'SocPref_', '_ALL', '_light', '_dark', '_2wpf', '_SocPref'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information 
  arenaCentersLocation:  # estimate from well offset positions
  arenaCentersColumns: 

TwoWeek2023_Fish1_TimeFlipped:
  dataPathMain: 2 week old - Fish1 FLIPPED in TIME # sub-path, under basePath, containing CSV files; or the parent path of subgroup folders; leave empty for user-input
  dataPathFull: # (Optional) full path containing CSV files or parent path of subgroup folders. If not empty, will override dataPathMain  fps: 25.0  # frames per second
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScalePathName: 2 week old - Fish1 FLIPPED in TIME # path for the CSV with image scale
  imageScaleFilename: ArenaCenters_SocPref_3456.csv
  imageScaleColumn: 4 # column (0-indexed) with image scale
  datasetColumns:  [0] # columns to concatenate to match dataset name 
  # filename of CSV file *in each data folder* with image offset filename
  datasetRemoveStrings: ['results_', 'SocPref_', '_ALL', '_light', '_dark', '_2wpf', '_SocPref'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information 
  arenaCentersPathName: 2 week old - Fish1 FLIPPED in TIME
  arenaCentersFilename: ArenaCenters_SocPref_3456.csv
  arenaCentersColumns: [5,6] # columns (0-indexed) with x,y arena centers