# experiment_paths_and_parameters

TwoWeekSept2025:
  fps: 25.0  # frames per second
  arena_radius_mm: 25.0  # arena radius, mm
  imageScale: 85.65 # image scale
  datasetColumns:  [0, 1]  # columns to concatenate to match dataset name
  # filename of CSV file *in each data folder* with image offset filename
  datasetRemoveStrings: ['results_', 'SocPref_', '_ALL'] # strings to remove from filenames and first column of the imageScale CSV to find matches. 
  offsetPositionsFilename: wellOffsetPositionsCSVfile.csv
  # Arena center location information
  arenaCentersLocation:  # estimate from well offset positions
  arenaCentersColumns: 
  subGroups: ['Dark_Cond_1', 'Light_Cond_2'] # 